export const USER_REQUEST = 'USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const INSERT_USER_SUCCESS = 'INSERT_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const RAISE_ERROR = 'RAISE_ERROR';
export const SELECT_USER = 'SELECT_USER';
export const CHANGE_ORDER = 'CHANGE_ORDER';